version: "1.0"
services:
  jena-fuseki:
    container_name: jena-fuseki
    build: .
    restart: always
    ports:
      - 3030:3030
    volumes:
      - fuseki:/app
    environment:
      - PORT=3030
      - ADMIN_PASSWORD=privatefusekiservice
volumes:
  fuseki:
    name: fuseki
